version: '3.9'

services:
  mysql-db:
    image: mysql
    restart: always
    shm_size: 128mb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: discord-clone
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'
